### ISSUE TITLE
Stars are Wrong

### ISSUE THREAD

**Issue by eyalabadi98** [Extrct/react-native-stars#1]
Hello,

I have the current code: 
`<View style={{ alignItems:'center' }} >
                    <Stars
                        value={1}
                        spacing={8}
                        count={5}
                        starSize={40}
                        backingColor='transparent'
                        fullStar={require('../../images/fullstar.png')}
                        emptyStar={require('../../images/emptystar.png')}
                        halfStar={require('../../images/halfstar.png')}
                    />
                </View>
            </View>`

but when I have a value of 1, it shows 2 stars. Same happens for any values put in

**Comment by 4umo** [comment]
Hi, I will take a look at this soon.
Thanks,
Austin

**Comment by 4umo** [comment]
So I just tested with version 0.45 and there seems to be a core issue with the module's behavior after recent RN changes. I'll try to fix the issue within the week, however if the changes are more fundamental to the module's image layering strategy it will take significantly more time to fix.

**Comment by 4umo** [comment]
The issue is that when using the module in default display mode (passing a value prop and not setting the opacity flag) the backingColor prop cannot be transparent. Otherwise the 'bar' that covers up the last star won't actually block out the underlying filled star to create the proper proportion. Apologies if this conflicts with your intended use of the component, but for now this is the hacky way the module is set up. Eventually I intend to introduce a more legitimate way of processing partial images using svgs so this will no longer be a constraint.

Here's the reference to this constraint in the readme props table:
" backingColor | (in Display Mode) color behind the component (cannot be transparent) "
